Provision Crunchy Bridge Database Instance from Admin View. Resolves DBAAS-541
RHODA-lab/rhoda-ci pull request #27
Opened 2022-05-16 18:23 UTC by harshkumarRH

With this PR, the following changes were implemented - 
- 2 Test cases were added to existing CrunchyDB Test Suite to cover Provisioning of Database Instance from Admin view for Valid and Invalid Provider Accounts
- Required Object Repository(_resources/object_repo/create_dbinstance_obj.resource_) and Keyword Resource file(_resources/keywords/create_instance.resource_) were added for the above task
- Logging method was changed to Log Info on both stdout and Log file
- Expansion of SideBar Menu was optimized

Marks tentative completion of subtask [DbaaS-451](https://issues.redhat.com/browse/DBAAS-541) under [DbaaS-514](https://issues.redhat.com/browse/DBAAS-514)

Signed-off-by: Harsh Kumar <hakumar@redhat.com>

2022-05-16 18:26 UTC, harshkumarRH commented
Logs attached for reference - [pull27_logs.zip](https://github.com/RHODA-lab/rhoda-ci/files/8702478/pull27_logs.zip)

2022-05-17 03:46 UTC, mrrajan commented on resources/keywords/create_instance.resource
> +    Sleep    3s
Please remove hard wait, instead use "Wait Until Keyword Succeeds" with keyword on line 20 like

Wait Until Keyword Succeeds     5x     2s     Select From List By Label ${drpDwnDBProvider} ${isv_name}

2022-05-17 03:47 UTC, mrrajan commented on resources/keywords/create_instance.resource
> +    Sleep    3s
Please remove hard wait and use Wait Until Keyword Succeeds

2022-05-17 03:48 UTC, mrrajan commented on resources/keywords/create_instance.resource
> +*** Settings ***
Shall we update the name of file as "provider_instance_admin.resource"

2022-05-17 03:49 UTC, mrrajan commented on resources/keywords/create_instance.resource
> +${instanceName}      ${EMPTY}
../keywords/deploy_instance_dev.resource already has this variable, we can just call it out instead of declaring it.

2022-05-17 03:53 UTC, mrrajan commented on resources/keywords/create_instance.resource
> +    Select From List By Label    ${drpDwnDevCatProviderAccount}     ${provaccname}
I hope keywords _User Selects DBProvider And Invalid Provider Account_ and _User Selects DBProvider And Provider Account_ can be combined. Along with ${isv_name} we can parameterize  ${provaccname}

2022-05-17 03:59 UTC, mrrajan commented on resources/keywords/create_instance.resource
> +User Enters Data To Create CrunchyDB Database Instance On Dev
Is this keyword to perform creating instance from Developers view? If yes, from line 42 to 45 we cannot select provider account and database provider, all these would be auto populated

2022-05-17 04:06 UTC, mrrajan commented on resources/keywords/create_provider_account.resource
> +    Sleep    8s         #Blind sleep to mitigate false failures due to auto page refresh
Instead of hard wait, use "Wait Until Keyword Succeeds" assigned with target element

2022-05-17 04:07 UTC, mrrajan commented on resources/keywords/create_provider_account.resource
> +    Run Keyword If    ${invalid}
I hope we can avoid this if we combine the keywords on create_instance.resource file

2022-05-17 04:07 UTC, mrrajan commented on resources/keywords/create_provider_account.resource
> +    Log    ${isvName}    console=yes
This can be removed

2022-05-17 04:20 UTC, mrrajan commented on utils/scripts/util.py
> +    # Field `name` should be a slug between 5 and 50 characters in length, containing only unicode characters, unicode numbers,hyphens, spaces, or underscores, and starting with a character.
I hope some isv have restrictions on instance name length like cockroach. We can get clarified and update this later.

2022-05-17 04:21 UTC, mrrajan requested changes
@harshkumarRH I have added some comments on PR

2022-05-17 13:59 UTC, ikanias commented on resources/keywords/create_instance.resource
> +    Wait Until Page Contains Element    ${drpDwnDevCatProviderAccount}     timeout=10s
${drpDwnDevCatProviderAccount} -->  ${drpDwnDevCatPrvdrAcct}

2022-05-17 14:37 UTC, ikanias approved these changes
LGTM except a few comments

2022-05-19 09:04 UTC, mrrajan approved these changes

2022-05-23 09:18 UTC, mrrajan commented
@harshkumarRH I hope we need to perform some maintenance for the patch release, shall we mark it as WIP and merge with master or keep this open until my maintenance efforts done? LMKYT

2022-05-23 10:20 UTC, harshkumarRH commented
@mrrajan This PR is only for the changes needed for Provisioning DB Instance, it should not include any changes for Patch release. I believe we should merge this PR and start with the maintenance changes after that. Any maintenance changes addressing the scenarios of this PR will be covered in subsequent PRs

2022-05-23 10:53 UTC, mrrajan approved these changes

2022-05-23 10:58 UTC, merged